spring:
  application:
    name: provider-management
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false
neo4j:
  uri: ${NEO4J_URI:bolt://localhost:7687}
  username: ${NEO4J_USERNAME:neo4j}
  password: ${NEO4J_PASSWORD:password}
  database: aton
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
